### PR TITLE
Update data collection with new OS apps icons

### PR DESCRIPTION
**Pull request by nCastle1**
Applied to both UWP and WPF

### CODE REVIEW

**Review by zwaap — COMMENTED** [review]
Nothing much to comment on from a code review perspective with this mostly being icon change/additions and there being no image preview in the diff.  I'll leave it to you and QA to decide whether this is good to go.

**Comment by mikewilburn** [comment]
@nCastle1 I'm still seeing remnants of the old icon showing in places.

Despite the correct icon showing in the Windows taskbar:
image

This is the icon that appears in the tray on the Mac side when running this via Parallels:
image

**Comment by nCastle1** [comment]
@mikewilburn is that icon kept in the dock permanently, or does it only show up when the app is opened? I wonder if Parallels is caching it. I recommend toggling the setting off and on to see if the new icon is pulled in.

In the settings for the VM:

Screen Shot 2019-07-10 at 9 51 10 PM

**Comment by mikewilburn** [comment]
Sure enough, that took care of it. Thanks for suggesting that @nCastle1.
image

**Pull request merged**
