### PR TITLE
Adds support for managing offline map while online

### PR DESCRIPTION
**Pull request by nCastle1**
The UI is now simplified so that the online and offline map status panels are converged into a single view.

The UI has also been updated to prevent interaction with critical elements (sign in/out, work on/offline, sync, delete map) while long-running operations are running. Covered operations are map sync and map download. Control style changes were made to enhance the appearance of disabled toggle buttons.

No release notes were added; I think the existing notes for the 1.3.0 release cover this kind of UI change.

### CODE REVIEW

**Review by esreli — CHANGES_REQUESTED** [review]
We might have created a misunderstanding between one another here. I do see the 'about this app' (info button) change in this build but other stated changes, those we've spoken about and those that are mentioned in the description of this PR, seem to be missing. 

Perhaps this is a misunderstanding on my part in what you intend to solve in this PR. Perhaps you can clear somethings up for me? In this PR review, I'm also submitting a few other suggestions as well.

> Note, this PR is derived from testing the _netcore_ DataCollection.WPF build.

## Misunderstandings

### Sync When Online

> The UI is now simplified so that the online and offline map status panels are converged into a single view.

It was my understanding this PR was attempting to unify the online/offline mode view. This unification was described in a previous [PR](https://github.com/Esri/data-collection-dotnet/pull/99#pullrequestreview-489133175) under **Platform Parity** -> **Sync Offline Map When Online**. As far as I can tell, there isn't much of a change here. 

| Working Online, Has Offline Map | Working Offline |
| --- | --- |
| Screen Shot 2020-10-19 at 3 36 44 PM | Screen Shot 2020-10-19 at 3 37 35 PM |

Am I missing something here?

### Download Map Job, Sign Out

The PR states,

> The UI has also been updated to prevent interaction with critical elements (sign in/out, work on/offline, sync, delete map) while long-running operations are running.

I decided to test this out and I was able to perform a 'critical' function while a long-running operation was running. Steps to repro:

1. Sign in
1. Perform generate offline map task
1. With task in progress, sign-out -> _I'm successfully able to sign-out_

## Other Suggestions

### UI Enhancement: About This App Down-Caret

We've established a pattern where buttons contained by the tool bar have a down-caret icon to signify they can be clicked. These existing buttons include the 'Work Mode' and 'Profile' buttons. I believe the new 'About This App' (Info) button would be better served with a down caret icon as well. I recognize the Info button icon is the most button-suggesting icon in the status bar but because the behavior of the Info button is similar to that of the other status bar buttons, presenting a view in fly-over presentation, I believe the UI parity would convey well to this button as well. Can we see what this looks like?

### Bug: Dismiss About This App

Clicking the 'About This App' (Info Button) reveals the info pane. Clicking the button again re-reveals the info pane. This creates an endless reveal loop where the only option to dismiss the pane is to click outside the info pane, absorbing the consequences of performing a click operation on the map view. It is my expectation that clicking the button while the pane is revealed would dismiss the pane. 

_For reference, click the 'profile' or 'work mode' buttons- either button reveals their respective pane & clicking the button again dismisses it._

### Link to Licenses and Acknowledgements

I'm on the fence about this feature...

On one hand, I think it's good practice for software to link end-users to the Runtime open source license agreement & 3rd party licenses links. On the other hand, OSA's primary customer is a developer, who has their own end users to consider. WRT either of these customers, I'm not so sure how much this feature benefits either the developer customer or their end-user. 

Ultimately, I don't think the OSA repo LICENSE document should not serve as the License agreement between our customer (external developers) and their end users. I recognize this choice is consistent with other App Configurations, configurations we can expect our developer customers to change when forking and building this app themselves.

So, I think this leaves us with two choices.

1. We place this URL in the app's config file (is it there already? It doesn't appear to be..)
1. We scrap this button altogether.

TBH, I would prefer we scrap it altogether, leaving it up to our developer customers to establish a licenses/acknowledgements pattern that works for them. Your thoughts here?

**Review by esreli — COMMENTED** [review]
I apologize for the misunderstanding in the last review. Because one build was created, I was under the impression that it captured both PRs. My mistake.

I was able to review this PR using the build you supplied and the earlier stated misunderstandings are cleared up. Locking the UI for a critical action works very well, and the single online/offline work mode view has changed as you stated, nice enhancements.

### UI Enhancement

I see what you did here; your reinterpretation of the mobile design for desktop. I recognize the need for a design augmentation, I generally like what you've come up with and i'd like to submit a suggestion to make the existing design even more usable (IMO).

I think the existing design can be improved in a few ways.

Screen Shot 2020-10-21 at 9 58 27 AM

#### 1. Work Online/Offline Buttons made more prominent

I'd like to see the Work Online & Work Offline buttons made more prominent. In the current design- when an offline map exists- either of these buttons, work mode depending, is the third button in a list of three. Can we give these buttons more prominence by moving their rank up to first?

#### 2. Horizontal Rules

I think this new design would be better served using horizontal rules to divide the view between online & offline map functionality. Specifically, I think a horizontal rule could be used to create an 'Offline Map' section with a title & last sync/downloaded dates included.

What are your thoughts on either of these?

### Potential Bug: Download Date & Last Sync Date

After performing a fresh download, I noticed the download date and last sync dates are different. It is my expectation that for a downloaded map that has not been synchronized, these two dates would match. Am I missing something here? How are these values derived?

Screen Shot 2020-10-21 at 8 23 43 AM

**Review by esreli — APPROVED** [review]
@nCastle1 your implementation is very nice, all features work as expected and the last sync/download dates appear to be in-sync. Nice work. One question remains, from where do you derive the download date?

**Comment by nCastle1** [comment]
@esreli Sorry for missing that question about the download date. There were a few bugs to fix so I addressed those but forgot to answer. 

* Download date comes from the offline map's local item (`OfflineMap.Item.Modified`). I believe that info is stored in the `package.info` file in the downloaded mmpk directory
* Sync date is stored as a setting after successful sync

Previously there was a time zone inconsistency. To address this, I now store the sync date setting in a format designed for round tripping (UTC with Z suffix); dates are converted to local time before display.

**Pull request merged**
